(function(){
'use strict';
const S=window.Support;if(!S)return;const {$,panel,esc,toast,fmt,masterRows,selectedClass,classControls,bindClassControls,loadTimetable,saveTimetable,chime,tickTone,speak}=S;
const quotes=['You do not have to understand everything at once. Learn one step at a time.','Slow progress is still progress. Keep the next step small and clear.','Not knowing yet is the beginning of learning.','A hard question is not a stop sign. Try a different strategy.','Mistakes show you what to work on next.','Ask for help when you need it. Strong learners do.','You can learn difficult things by breaking them into smaller parts.','Getting stuck does not mean you cannot learn it. It means you need a next move.','One careful step is better than rushing through ten.','If the work feels hard, choose one part you can do first.','Every time you correct a mistake, your understanding gets stronger.','You do not need to be the fastest learner. You need to keep learning.','When you feel unsure, use a strategy instead of giving up.'];
const questionPrompts=['Who?','What?','When?','Where?','Why?','How?','Explain','Compare','Predict','What if…?','What evidence?','Give a reason','How do you know?','Describe'];
const reflectPrompts=['What did you learn?','What was difficult?','What helped you?','What are you more confident about now?','What strategy worked for you?','What will you try next time?'];
const breaks=['10 shoulder rolls','Reach high, then touch your toes','Stand and stretch for 20 seconds','5 slow star jumps','Shake out your hands and legs','March quietly on the spot','Take 5 slow breaths','Stretch your arms wide, then relax'];
function renderTimer(){
 let base=300,sec=base,running=false,id=null,music=true,beatId=null;
 panel.innerHTML=`<div class="eyebrow">Focus time</div><div class="timerRing" id="ring"><div class="timerValue" id="time">05:00</div></div><div class="supportText">See how much time is left. Work calmly, one step at a time.</div><div class="controls">${[1,3,5,10,15].map(m=>`<button class="btn" data-min="${m}">${m} min</button>`).join('')}<button class="btn soft" id="music">♫ Calm music: On</button></div><div class="controls" style="margin-top:12px"><button class="btn primary" id="start">▶ Start</button><button class="btn" id="reset">↺ Reset</button></div>`;
 const time=$('#time'),ring=$('#ring'),start=$('#start'),musicBtn=$('#music');
 function stopBeat(){clearInterval(beatId);beatId=null}function startBeat(){stopBeat();if(!music)return;let n=0;beatId=setInterval(()=>{if(!running||!music)return;S.tone([262,330,392,330][n++%4],.22,.025,'sine')},900)}
 function draw(){time.textContent=fmt(sec);ring.style.setProperty('--progress',`${base?Math.max(0,sec/base*100):100}%`);start.textContent=running?'Ⅱ Pause':'▶ Start'}
 function stop(){clearInterval(id);id=null;running=false;stopBeat();draw()}function go(){if(running){stop();return}running=true;draw();startBeat();id=setInterval(()=>{sec--;draw();if(sec<=0){stop();chime();toast('Time is up')}},1000)}
 document.querySelectorAll('[data-min]').forEach(b=>b.onclick=()=>{stop();base=sec=+b.dataset.min*60;draw()});start.onclick=go;$('#reset').onclick=()=>{stop();sec=base;draw()};musicBtn.onclick=()=>{music=!music;musicBtn.textContent='♫ Calm music: '+(music?'On':'Off');if(running){music?startBeat():stopBeat()}};draw()
}
function renderTransition(){
 let base=60,sec=60,running=false,id=null,music=true,beatId=null;
 panel.innerHTML=`<div class="eyebrow">Change activity</div><div class="timerRing" id="ring"><div class="timerValue" id="time">01:00</div></div><div class="hero small" id="cue">Move safely • Be ready</div><div class="supportText">Finish the transition before the countdown ends.</div><div class="controls">${[30,60,120].map(s=>`<button class="btn" data-sec="${s}">${s<60?s+' sec':s/60+' min'}</button>`).join('')}<button class="btn soft" id="music">♫ Music: On</button><button class="btn primary" id="start">▶ Start transition</button></div>`;
 const ring=$('#ring'),time=$('#time'),start=$('#start'),musicBtn=$('#music');
 function stopBeat(){clearTimeout(beatId);beatId=null}function beat(){if(!running||!music)return;tickTone();beatId=setTimeout(beat,sec<=10?300:480)}function draw(){time.textContent=fmt(sec);ring.style.setProperty('--progress',`${Math.max(0,sec/base*100)}%`);ring.classList.toggle('pulse',running&&sec<=10);start.textContent=running?'■ Stop':'▶ Start transition'}function stop(){clearInterval(id);id=null;running=false;stopBeat();draw()}
 function go(){if(running){stop();return}running=true;$('#cue').textContent='Move safely • Be ready';draw();beat();id=setInterval(()=>{sec--;draw();if(sec<=0){stop();chime();$('#cue').textContent='Ready!';toast('Transition complete')}},1000)}
 document.querySelectorAll('[data-sec]').forEach(b=>b.onclick=()=>{stop();base=sec=+b.dataset.sec;$('#cue').textContent='Move safely • Be ready';draw()});musicBtn.onclick=()=>{music=!music;musicBtn.textContent='♫ Music: '+(music?'On':'Off');if(running){stopBeat();if(music)beat()}};start.onclick=go;draw()
}
function renderAttention(){
 panel.innerHTML=`<div class="eyebrow">Attention cue</div><div class="signal" id="signal">Eyes here</div><div class="supportText">A short, predictable signal tells everyone when to stop, look and listen.</div><button class="btn primary" id="signalBtn">🔔 Signal now</button>`;
 let busy=false;$('#signalBtn').onclick=()=>{if(busy)return;busy=true;const seq=['3','2','1','Eyes here'];let i=0;chime();const el=$('#signal');function next(){el.textContent=seq[i];el.classList.remove('pulse');void el.offsetWidth;el.classList.add('pulse');i++;if(i<seq.length)setTimeout(next,650);else setTimeout(()=>{el.classList.remove('pulse');busy=false},800)}next()}
}
function renderNoise(){
 const levels=[['🤫','Silent','No talking'],['🫢','Whisper','Only the person beside you can hear'],['👥','Partner','Talk to your partner'],['🗣️','Group','Your group can hear you'],['🎤','Presentation','One voice for the whole class']];
 panel.innerHTML=`<div class="eyebrow">Voice level</div><div class="noiseBadge"><div><div class="noiseBig" id="noiseBig">Silent</div><div class="supportText" id="noiseSub" style="margin:8px auto 0">No talking</div></div></div><div class="choiceGrid">${levels.map((x,i)=>`<button class="choice ${i===0?'active':''}" data-i="${i}"><span class="choiceIcon">${x[0]}</span><span class="choiceTitle">${x[1]}</span><span class="choiceSub">${x[2]}</span></button>`).join('')}</div>`;
 document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-i]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const l=levels[+b.dataset.i];$('#noiseBig').textContent=l[1];$('#noiseSub').textContent=l[2]})
}
function renderQuestion(){
 panel.innerHTML=`<div class="eyebrow">Thinking prompt</div><div class="spinnerDisc" id="disc"><div class="spinnerWord" id="word">How do you know?</div></div><div class="supportText">Use the prompt to explain your thinking, not just give an answer.</div><button class="btn primary" id="spin">↻ Spin a question</button><div class="controls" style="margin-top:12px"><select class="classSelect" id="promptSelect">${questionPrompts.map(x=>`<option>${esc(x)}</option>`).join('')}</select><button class="btn" id="choosePrompt">Use this prompt</button></div>`;
 $('#spin').onclick=()=>{const d=$('#disc');d.classList.remove('spin');void d.offsetWidth;d.classList.add('spin');let n=0;const id=setInterval(()=>{$('#word').textContent=questionPrompts[Math.floor(Math.random()*questionPrompts.length)];if(++n>10){clearInterval(id);d.classList.remove('spin')}},65)};$('#choosePrompt').onclick=()=>{$('#word').textContent=$('#promptSelect').value}
}
function renderConfidence(){
 panel.innerHTML=`<div class="eyebrow">How is learning going?</div><div class="hero small">Show where you are now</div><div class="supportText">There is no wrong choice. This helps the teacher know what support you need.</div><div class="confidenceGrid"><button class="confidence"><span class="face">🆘</span><span class="label">I need help</span><span class="sub">Please support me</span></button><button class="confidence"><span class="face">🌱</span><span class="label">I’m getting there</span><span class="sub">I need more practice</span></button><button class="confidence"><span class="face">✅</span><span class="label">I can do it</span><span class="sub">I can try independently</span></button><button class="confidence"><span class="face">💡</span><span class="label">I can explain it</span><span class="sub">I can help someone else</span></button></div><div class="resultCard hidden" id="confidenceResult"><div class="resultMeta">Class response cue</div><div class="hero small" id="confidenceText"></div></div>`;
 document.querySelectorAll('.confidence').forEach(b=>b.onclick=()=>{const text=b.querySelector('.label').textContent;$('#confidenceText').textContent=text;$('#confidenceResult').classList.remove('hidden');toast(text)})
}
function renderPick(){
 panel.innerHTML=`${classControls()}<div class="eyebrow">Fair participation</div><div class="resultCard"><div class="resultMeta" id="pickMeta">Ready to choose</div><div class="resultName" id="pickName">?</div></div><div class="supportText">Everyone gets a fair chance. Pick without replacement until the round is complete.</div><div class="controls"><button class="btn primary" id="pick">🎯 Pick a pupil</button><button class="btn" id="resetPick">↺ New round</button></div><div class="miniHint" id="sourceHint"></div>`;
 bindClassControls(renderPick);const rows=masterRows(),pool=rows.map(r=>r.pupil).filter(Boolean);let remaining=[...pool];$('#sourceHint').textContent=pool.length?`${pool.length} pupils loaded from ${selectedClass()}.`:'Add a class or pupils in Class Organisation first.';
 $('#pick').onclick=()=>{if(!remaining.length){remaining=[...pool];if(!remaining.length){toast('Add pupils first');return}}const i=Math.floor(Math.random()*remaining.length),name=remaining.splice(i,1)[0];$('#pickName').textContent=name;$('#pickMeta').textContent=`${remaining.length} left in this round`;chime()};$('#resetPick').onclick=()=>{remaining=[...pool];$('#pickName').textContent='?';$('#pickMeta').textContent='New round ready'}
}
function renderGroups(){
 panel.innerHTML=`${classControls()}<div class="eyebrow">Random grouping</div><div class="hero small">Make groups</div><div class="supportText">Names come from the class master sheet so the list stays consistent.</div><div class="controls"><span style="font-weight:900;color:var(--navy)">Group size</span>${[2,3,4,5].map(n=>`<button class="btn size ${n===4?'primary':''}" data-size="${n}">${n}</button>`).join('')}<button class="btn primary" id="make">👥 Make groups</button></div><div class="groups" id="groups"></div><div class="miniHint" id="sourceHint"></div>`;
 bindClassControls(renderGroups);let size=4;document.querySelectorAll('.size').forEach(b=>b.onclick=()=>{size=+b.dataset.size;document.querySelectorAll('.size').forEach(x=>x.classList.remove('primary'));b.classList.add('primary')});const names=masterRows().map(r=>r.pupil).filter(Boolean);$('#sourceHint').textContent=names.length?`${names.length} pupils loaded from ${selectedClass()}.`:'Add a class or pupils first.';
 $('#make').onclick=()=>{if(!names.length){toast('Add pupils first');return}const shuffled=[...names];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}const gs=[];for(let i=0;i<shuffled.length;i+=size)gs.push(shuffled.slice(i,i+size));$('#groups').innerHTML=gs.map((g,i)=>`<div class="group"><h3>Group ${i+1}</h3>${g.map(n=>`<div class="member">${esc(n)}</div>`).join('')}</div>`).join('')}
}
function renderBreak(){
 let idx=Math.floor(Math.random()*breaks.length),sec=30,id=null;
 panel.innerHTML=`<div class="eyebrow">Short reset</div><div class="breakMove" id="move">${breaks[idx]}</div><div class="timerRing" id="ring" style="width:min(42vw,300px)"><div class="timerValue" id="time" style="font-size:clamp(46px,8vw,76px)">00:30</div></div><div class="supportText">Move safely. Stop if anything feels uncomfortable.</div><div class="controls"><button class="btn primary" id="start">▶ Start 30 sec</button><button class="btn" id="next">↻ Another break</button></div>`;
 const draw=()=>{$('#time').textContent=fmt(sec);$('#ring').style.setProperty('--progress',`${sec/30*100}%`)};$('#start').onclick=()=>{clearInterval(id);sec=30;draw();id=setInterval(()=>{sec--;draw();if(sec<=0){clearInterval(id);chime();toast('Ready to learn again')}},1000)};$('#next').onclick=()=>{idx=(idx+1+Math.floor(Math.random()*(breaks.length-1)))%breaks.length;$('#move').textContent=breaks[idx]}
}
function renderReflect(){
 let i=0;panel.innerHTML=`<div class="eyebrow">Learning reflection</div><div class="hero small" id="prompt">${reflectPrompts[i]}</div><div class="supportText">Think quietly first. Then share, write or keep your answer in mind.</div><button class="btn primary" id="next">↻ Another prompt</button>`;$('#next').onclick=()=>{i=(i+1+Math.floor(Math.random()*(reflectPrompts.length-1)))%reflectPrompts.length;$('#prompt').textContent=reflectPrompts[i]}
}
function dayQuote(){const d=new Date(),day=Math.floor(new Date(d.getFullYear(),d.getMonth(),d.getDate())/86400000);return quotes[((day%quotes.length)+quotes.length)%quotes.length]}
function renderQuote(){
 panel.innerHTML=`<div class="eyebrow">A thought for today</div><div class="quoteMark">“</div><div class="quoteText" id="quote">${esc(dayQuote())}</div><div class="supportText">Learning can be difficult and still be worth continuing.</div><div class="controls"><button class="btn primary" id="read">🔊 Read aloud</button><button class="btn" id="another">✨ Another quote</button></div>`;$('#read').onclick=()=>speak($('#quote').textContent);$('#another').onclick=()=>{$('#quote').textContent=quotes[Math.floor(Math.random()*quotes.length)]}
}
function renderTimetable(){
 let rows=loadTimetable();panel.innerHTML=`${classControls()}<div class="eyebrow">Today at a glance</div><div class="hero small">What happens next?</div><div class="supportText">A clear sequence can make the day feel more predictable.</div><div class="timetable" id="rows"></div><div class="controls"><button class="btn primary" id="add">＋ Add item</button><button class="btn soft" id="project">▣ Pupil view</button></div>`;bindClassControls(renderTimetable);
 function draw(){const box=$('#rows');box.innerHTML=rows.length?rows.map((r,i)=>`<div class="timeRow"><input class="timeInput" data-i="${i}" data-k="time" value="${esc(r.time)}" placeholder="8:00"><input class="activityInput" data-i="${i}" data-k="activity" value="${esc(r.activity)}" placeholder="Activity"><button class="removeRow" data-del="${i}">×</button></div>`).join(''):'<div class="emptyState">No timetable items yet. Add the first activity.</div>';box.querySelectorAll('input').forEach(x=>x.oninput=()=>{rows[+x.dataset.i][x.dataset.k]=x.value;saveTimetable(rows)});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{rows.splice(+b.dataset.del,1);saveTimetable(rows);draw()})}
 $('#add').onclick=()=>{rows.push({time:'',activity:'New activity'});saveTimetable(rows);draw()};$('#project').onclick=()=>{if(!rows.length){toast('Add timetable items first');return}panel.innerHTML=`<div class="eyebrow">Today's plan</div><div class="hero small">${esc(selectedClass()||'Today')}</div><div class="timetable">${rows.map(r=>`<div class="timeRow" style="grid-template-columns:120px 1fr"><div class="timeInput" style="display:flex;align-items:center">${esc(r.time||'—')}</div><div class="activityInput" style="display:flex;align-items:center;font-size:clamp(18px,2.2vw,30px)">${esc(r.activity||'')}</div></div>`).join('')}</div><button class="btn" id="editAgain">← Edit timetable</button>`;$('#editAgain').onclick=renderTimetable};draw()
}
function render(){switch(S.slug){case'timer-calm-music':renderTimer();break;case'transition-countdown':renderTransition();break;case'attention-signal':renderAttention();break;case'noise-level':renderNoise();break;case'question-spinner':renderQuestion();break;case'confidence-check':renderConfidence();break;case'pick-a-pupil':renderPick();break;case'make-groups':renderGroups();break;case'brain-break':renderBreak();break;case'reflect':renderReflect();break;case'quote-of-the-day':renderQuote();break;case'daily-visual-timetable':renderTimetable();break;default:renderTimer()}}
window.addEventListener('storage',e=>{if([S.CC_STORE,S.MASTER_STORE].includes(e.key)&&['pick-a-pupil','make-groups','daily-visual-timetable'].includes(S.slug))render()});render();S.attachLauncher();
})();