'use strict';
const I18N={
 en:{lang:'en',title:'Whiteboard',subtitle:'Write, draw and explain to the class.',pen:'✏️ Pen',text:'T Text',eraser:'⌫ Eraser',thickness:'Thickness',textSize:'Text size',undo:'↶ Undo',grid:'▦ Grid',blank:'□ Blank',full:'⛶ Full screen',exitFull:'↙ Exit full screen',clear:'Clear',watermark:'Whiteboard',prompt:'Type the text to place on the whiteboard:',undoDone:'Last action undone',cleared:'Whiteboard cleared',clearAsk:'Clear the whole whiteboard?',fullFail:'Full screen is not available here',penWord:'Pen',textWord:'Text',eraserWord:'Eraser',colours:{'#17324d':'navy','#2563eb':'blue','#dc2626':'red','#15803d':'green','#7c3aed':'purple'}},
 zh:{lang:'zh-SG',title:'白板',subtitle:'书写、绘图并向全班讲解。',pen:'✏️ 画笔',text:'T 文字',eraser:'⌫ 橡皮擦',thickness:'粗细',textSize:'字号',undo:'↶ 撤销',grid:'▦ 方格',blank:'□ 空白',full:'⛶ 全屏',exitFull:'↙ 退出全屏',clear:'清除',watermark:'白板',prompt:'请输入要放在白板上的文字：',undoDone:'已撤销上一步',cleared:'白板已清除',clearAsk:'清除整块白板吗？',fullFail:'这里无法使用全屏模式',penWord:'画笔',textWord:'文字',eraserWord:'橡皮擦',colours:{'#17324d':'深蓝','#2563eb':'蓝','#dc2626':'红','#15803d':'绿','#7c3aed':'紫'}},
 ms:{lang:'ms-SG',title:'Papan Putih',subtitle:'Tulis, lukis dan terangkan kepada kelas.',pen:'✏️ Pen',text:'T Teks',eraser:'⌫ Pemadam',thickness:'Ketebalan',textSize:'Saiz teks',undo:'↶ Buat asal',grid:'▦ Grid',blank:'□ Kosong',full:'⛶ Skrin penuh',exitFull:'↙ Keluar skrin penuh',clear:'Kosongkan',watermark:'Papan Putih',prompt:'Taip teks untuk diletakkan pada papan putih:',undoDone:'Tindakan terakhir dibuat asal',cleared:'Papan putih dikosongkan',clearAsk:'Kosongkan seluruh papan putih?',fullFail:'Skrin penuh tidak tersedia di sini',penWord:'Pen',textWord:'Teks',eraserWord:'Pemadam',colours:{'#17324d':'biru tua','#2563eb':'biru','#dc2626':'merah','#15803d':'hijau','#7c3aed':'ungu'}},
 ta:{lang:'ta-SG',title:'வெண்பலகை',subtitle:'எழுதி, வரைந்து, வகுப்பிற்கு விளக்குங்கள்.',pen:'✏️ பேனா',text:'T உரை',eraser:'⌫ அழிப்பான்',thickness:'தடிமன்',textSize:'உரை அளவு',undo:'↶ செயல்நீக்கு',grid:'▦ கட்டம்',blank:'□ வெற்று',full:'⛶ முழுத் திரை',exitFull:'↙ முழுத் திரையிலிருந்து வெளியேறு',clear:'அழி',watermark:'வெண்பலகை',prompt:'வெண்பலகையில் இட வேண்டிய உரையைத் தட்டச்சு செய்யுங்கள்:',undoDone:'கடைசி செயல் செயல்நீக்கப்பட்டது',cleared:'வெண்பலகை அழிக்கப்பட்டது',clearAsk:'முழு வெண்பலகையையும் அழிக்கவா?',fullFail:'முழுத் திரை இங்கு கிடைக்கவில்லை',penWord:'பேனா',textWord:'உரை',eraserWord:'அழிப்பான்',colours:{'#17324d':'கருநீலம்','#2563eb':'நீலம்','#dc2626':'சிவப்பு','#15803d':'பச்சை','#7c3aed':'ஊதா'}}
};
const edition=(new URLSearchParams(location.search).get('edition')||'en').toLowerCase(),L=I18N[edition]||I18N.en;document.documentElement.lang=L.lang;document.title=L.title+' • Classroom Companion';
const canvas=document.getElementById('board'),wrap=document.getElementById('boardWrap'),ctx=canvas.getContext('2d');
const penBtn=document.getElementById('penBtn'),textBtn=document.getElementById('textBtn'),eraserBtn=document.getElementById('eraserBtn'),undoBtn=document.getElementById('undoBtn'),gridBtn=document.getElementById('gridBtn'),fullBtn=document.getElementById('fullBtn'),clearBtn=document.getElementById('clearBtn'),size=document.getElementById('size'),sizeValue=document.getElementById('sizeValue'),sizeLabel=document.getElementById('sizeLabel'),modeBadge=document.getElementById('modeBadge'),toast=document.getElementById('toast');
document.getElementById('boardTitle').textContent=L.title;document.getElementById('boardSubtitle').textContent=L.subtitle;penBtn.textContent=L.pen;textBtn.textContent=L.text;eraserBtn.textContent=L.eraser;undoBtn.textContent=L.undo;clearBtn.textContent=L.clear;wrap.dataset.watermark=L.watermark;
let strokes=[],current=null,tool='pen',colour='#17324d',drawing=false,grid=true,cssW=1,cssH=1;
function say(text){toast.textContent=text;toast.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toast.classList.remove('show'),1400)}
function colourName(c){return L.colours[c]||c}function fontSize(){return Math.max(18,Number(size.value)*3)}
function syncUi(){penBtn.classList.toggle('active',tool==='pen');textBtn.classList.toggle('active',tool==='text');eraserBtn.classList.toggle('active',tool==='eraser');undoBtn.disabled=strokes.length===0;sizeLabel.textContent=tool==='text'?L.textSize:L.thickness;sizeValue.textContent=tool==='text'?fontSize():size.value;modeBadge.textContent=tool==='eraser'?`${L.eraserWord} · ${Math.max(12,Number(size.value)*2)} px`:tool==='text'?`${L.textWord} · ${colourName(colour)} · ${fontSize()} px`:`${L.penWord} · ${colourName(colour)} · ${size.value} px`;gridBtn.setAttribute('aria-pressed',String(grid));gridBtn.textContent=grid?L.grid:L.blank;fullBtn.textContent=document.fullscreenElement?L.exitFull:L.full;canvas.style.cursor=tool==='text'?'text':'crosshair';document.querySelectorAll('.colour').forEach(b=>b.classList.toggle('active',b.dataset.colour===colour))}
function resize(){const r=wrap.getBoundingClientRect();cssW=Math.max(1,r.width);cssH=Math.max(1,r.height);const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(cssW*dpr);canvas.height=Math.round(cssH*dpr);canvas.style.width=cssW+'px';canvas.style.height=cssH+'px';ctx.setTransform(dpr,0,0,dpr,0,0);redraw()}
function xy(p){return{x:p.x*cssW,y:p.y*cssH}}
function drawStroke(s){if(s.type==='text'){const p=xy(s);ctx.save();ctx.globalCompositeOperation='source-over';ctx.fillStyle=s.colour;ctx.font=`700 ${s.size}px Inter,system-ui,sans-serif`;ctx.textBaseline='top';ctx.fillText(s.text,p.x,p.y);ctx.restore();return}if(!s.points?.length)return;ctx.save();ctx.globalCompositeOperation=s.erase?'destination-out':'source-over';ctx.strokeStyle=s.erase?'rgba(0,0,0,1)':s.colour;ctx.fillStyle=s.erase?'rgba(0,0,0,1)':s.colour;ctx.lineWidth=s.size;ctx.lineCap='round';ctx.lineJoin='round';if(s.points.length===1){const p=xy(s.points[0]);ctx.beginPath();ctx.arc(p.x,p.y,s.size/2,0,Math.PI*2);ctx.fill();ctx.restore();return}ctx.beginPath();const first=xy(s.points[0]);ctx.moveTo(first.x,first.y);for(let i=1;i<s.points.length;i++){const p=xy(s.points[i]);ctx.lineTo(p.x,p.y)}ctx.stroke();ctx.restore()}
function redraw(){ctx.clearRect(0,0,cssW,cssH);for(const s of strokes)drawStroke(s);if(current)drawStroke(current)}
function pointFromEvent(e){const r=canvas.getBoundingClientRect();return{x:Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),y:Math.min(1,Math.max(0,(e.clientY-r.top)/r.height))}}
function start(e){if(e.button!==undefined&&e.button!==0)return;if(tool==='text'){const p=pointFromEvent(e),text=prompt(L.prompt,'');if(text&&text.trim()){strokes.push({type:'text',x:p.x,y:p.y,text:text.trim(),colour,size:fontSize()});redraw();syncUi()}e.preventDefault();return}drawing=true;canvas.setPointerCapture?.(e.pointerId);current={erase:tool==='eraser',colour,size:tool==='eraser'?Math.max(12,Number(size.value)*2):Number(size.value),points:[pointFromEvent(e)]};redraw();e.preventDefault()}
function move(e){if(!drawing||!current)return;const p=pointFromEvent(e),last=current.points.at(-1);if(!last||Math.hypot((p.x-last.x)*cssW,(p.y-last.y)*cssH)>=1.5){current.points.push(p);redraw()}e.preventDefault()}
function end(e){if(!drawing||!current)return;drawing=false;strokes.push(current);current=null;syncUi();redraw();try{canvas.releasePointerCapture?.(e.pointerId)}catch{}e.preventDefault()}
canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
penBtn.onclick=()=>{tool='pen';syncUi()};textBtn.onclick=()=>{tool='text';syncUi()};eraserBtn.onclick=()=>{tool='eraser';syncUi()};document.querySelectorAll('.colour').forEach(b=>b.onclick=()=>{colour=b.dataset.colour;if(tool==='eraser')tool='pen';syncUi()});size.oninput=syncUi;undoBtn.onclick=()=>{if(strokes.length){strokes.pop();redraw();syncUi();say(L.undoDone)}};gridBtn.onclick=()=>{grid=!grid;wrap.classList.toggle('grid',grid);syncUi()};clearBtn.onclick=()=>{if(!strokes.length)return;if(confirm(L.clearAsk)){strokes=[];current=null;redraw();syncUi();say(L.cleared)}};fullBtn.onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{say(L.fullFail)}};document.addEventListener('fullscreenchange',()=>{syncUi();setTimeout(resize,60)});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undoBtn.click()}else if(e.key==='e'&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName)){tool='eraser';syncUi()}else if(e.key==='p'&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName)){tool='pen';syncUi()}else if(e.key==='t'&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName)){tool='text';syncUi()}});new ResizeObserver(()=>resize()).observe(wrap);window.addEventListener('resize',resize);syncUi();requestAnimationFrame(resize);
